// <auto-generated />
using System;
using System.Collections.Generic;
using IdentityService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260127112717_Inittial")]
    partial class Inittial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Domain.Aggregates.PermissionAggregate.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.ProvinceAggregate.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ProvinceName");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProvinceName = "An Giang"
                        },
                        new
                        {
                            Id = 2,
                            ProvinceName = "Bắc Ninh"
                        },
                        new
                        {
                            Id = 3,
                            ProvinceName = "Cà Mau"
                        },
                        new
                        {
                            Id = 4,
                            ProvinceName = "Cao Bằng"
                        },
                        new
                        {
                            Id = 5,
                            ProvinceName = "TP. Cần Thơ"
                        },
                        new
                        {
                            Id = 6,
                            ProvinceName = "TP. Đà Nẵng"
                        },
                        new
                        {
                            Id = 7,
                            ProvinceName = "Đắk Lắk"
                        },
                        new
                        {
                            Id = 8,
                            ProvinceName = "Đồng Nai"
                        },
                        new
                        {
                            Id = 9,
                            ProvinceName = "Đồng Tháp"
                        },
                        new
                        {
                            Id = 10,
                            ProvinceName = "Điện Biên"
                        },
                        new
                        {
                            Id = 11,
                            ProvinceName = "Gia Lai"
                        },
                        new
                        {
                            Id = 12,
                            ProvinceName = "TP. Hà Nội"
                        },
                        new
                        {
                            Id = 13,
                            ProvinceName = "Hà Tĩnh"
                        },
                        new
                        {
                            Id = 14,
                            ProvinceName = "TP. Hải Phòng"
                        },
                        new
                        {
                            Id = 15,
                            ProvinceName = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 16,
                            ProvinceName = "Hưng Yên"
                        },
                        new
                        {
                            Id = 17,
                            ProvinceName = "Khánh Hòa"
                        },
                        new
                        {
                            Id = 18,
                            ProvinceName = "Kon Tum"
                        },
                        new
                        {
                            Id = 19,
                            ProvinceName = "Lai Châu"
                        },
                        new
                        {
                            Id = 20,
                            ProvinceName = "Lạng Sơn"
                        },
                        new
                        {
                            Id = 21,
                            ProvinceName = "Lào Cai"
                        },
                        new
                        {
                            Id = 22,
                            ProvinceName = "Lâm Đồng"
                        },
                        new
                        {
                            Id = 23,
                            ProvinceName = "Nghệ An"
                        },
                        new
                        {
                            Id = 24,
                            ProvinceName = "Ninh Bình"
                        },
                        new
                        {
                            Id = 25,
                            ProvinceName = "Phú Thọ"
                        },
                        new
                        {
                            Id = 26,
                            ProvinceName = "Quảng Ninh"
                        },
                        new
                        {
                            Id = 27,
                            ProvinceName = "Quảng Ngãi"
                        },
                        new
                        {
                            Id = 28,
                            ProvinceName = "Quảng Trị"
                        },
                        new
                        {
                            Id = 29,
                            ProvinceName = "Sơn La"
                        },
                        new
                        {
                            Id = 30,
                            ProvinceName = "Tây Ninh"
                        },
                        new
                        {
                            Id = 31,
                            ProvinceName = "Thanh Hóa"
                        },
                        new
                        {
                            Id = 32,
                            ProvinceName = "Thái Nguyên"
                        },
                        new
                        {
                            Id = 33,
                            ProvinceName = "Tuyên Quang"
                        },
                        new
                        {
                            Id = 34,
                            ProvinceName = "Vĩnh Long"
                        });
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RefreshTokenAggregate.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("IsRevoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RevokeAt");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RoleAggregate.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RoleAggregate.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRoles_UserId_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.UserAggregate.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Address");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Note");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("ProvinceId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserAddress_UserId");

                    b.ToTable("UserAddresses", (string)null);
                });

            modelBuilder.Entity("IdentityService.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RefreshTokenAggregate.RefreshToken", b =>
                {
                    b.HasOne("IdentityService.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RoleAggregate.UserRole", b =>
                {
                    b.HasOne("IdentityService.Domain.Aggregates.RoleAggregate.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("IdentityService.Domain.Aggregates.UserAggregate.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("IdentityService.Domain.Aggregates.UserAggregate.UserPhone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_User_Phone");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("IdentityService.Domain.Aggregates.UserAggregate.UserEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_User_Email");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("IdentityService.Domain.Aggregates.UserAggregate.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("UserName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.UserAggregate.UserAddress", b =>
                {
                    b.HasOne("IdentityService.Domain.Aggregates.ProvinceAggregate.Province", "Province")
                        .WithMany("UserAddresses")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IdentityService.Domain.Aggregates.UserAggregate.UserPhone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserAddressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Phone");

                            b1.HasKey("UserAddressId");

                            b1.ToTable("UserAddresses");

                            b1.WithOwner()
                                .HasForeignKey("UserAddressId");
                        });

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.ProvinceAggregate.Province", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.RoleAggregate.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IdentityService.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
