networks:
  evnet:
    name: evnet


volumes:
  pg_identity: {}
  pg_catalog: {}
  uploads: {}
  redis-data:
    driver: local
  catalog-redis-data:
    driver: local
  catalog-kafka-data:
    driver: local
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local


services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/frontend/dist:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - api-gateway
    networks:
      - evnet
  redis:
    image: redis:7-alpine
    container_name: identity-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - evnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  catalog-redis:
    image: redis:7-alpine
    container_name: catalog-redis
    ports:
      - "6380:6380"
    volumes:
      - catalog-redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - evnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  ###--------- Kafka --------###
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - evnet
    healthcheck:
      test: echo stat | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - catalog-kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình Listener: nội bộ Docker dùng cổng 29092, bên ngoài dùng cổng 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - evnet
    healthcheck:
      # Sử dụng nc (netcat) để check cổng 9092 đã mở chưa cho nhẹ và chính xác
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s      # Cứ 10 giây check 1 lần (để cho nó thở)
      timeout: 5s       # Chờ phản hồi trong 5 giây
      retries: 5        # Thử lại 5 lần trước khi báo lỗi
      start_period: 15s # Cho phép Kafka có 15 giây đầu tiên để khởi động thoải mái không tính lỗi

  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:80
    networks:
      - evnet
    depends_on:
      - identity-api
      - catalog-api
    restart: unless-stopped
  identity-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${IDENTITY_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD}
      POSTGRES_DB: ${IDENTITY_DB_NAME}
    ports:
      - "5435:5432"   # để connect từ host
    volumes:
      - pg_identity:/var/lib/postgresql/data
    networks: [evnet]

  identity-api:
    build:
      context: .
      dockerfile: src/services/identity-service/IdentityService.Api/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ASPNETCORE_URLS: http://+:8080; https://+:8081
      ConnectionStrings__Default: "Host=identity-db;Port=5432;Database=${IDENTITY_DB_NAME};Username=${IDENTITY_DB_USER};Password=${IDENTITY_DB_PASSWORD}"
    depends_on:
      - identity-db
    ports:
      - "8103:8080" 
    networks: [evnet]
    restart: unless-stopped

  catalog-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_DB: ${CATALOG_DB_NAME}
    ports:
      - "5436:5432"   # để connect từ host
    volumes:
      - pg_catalog:/var/lib/postgresql/data
    networks: [evnet]
  catalog-api:
    build:
      context: .
      dockerfile: src/services/catalog-service/CatalogService.Api/Dockerfile
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ASPNETCORE_URLS: http://+:8080
      GrpcSettings__IdentityServiceUrl: http://identity-api:8081
      LocalFileStorage__BasePath: "wwwroot/uploads"
      ConnectionStrings__Default: "Host=catalog-db;Port=5432;Database=${CATALOG_DB_NAME};Username=${CATALOG_DB_USER};Password=${CATALOG_DB_PASSWORD}"
      Kafka__BootstrapServers: "kafka:29092"
    depends_on:
      catalog-db:
        condition: service_started
      catalog-kafka:
        condition: service_healthy
    ports:
      - "8104:8080"
    volumes:
      - uploads:/app/wwwroot/uploads
    networks: [evnet]
    restart: unless-stopped
