networks:
  evnet:
    name: evnet


volumes:
  pg_identity: {}
  pg_catalog: {}
  uploads: {}
  redis-data:
    driver: local


services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/frontend/dist:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - api-gateway
    networks:
      - evnet
  redis:
    image: redis:7-alpine
    container_name: identity-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - evnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:80
    networks:
      - evnet
    depends_on:
      - identity-api
    restart: unless-stopped
  identity-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${IDENTITY_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD}
      POSTGRES_DB: ${IDENTITY_DB_NAME}
    ports:
      - "5435:5432"   # để connect từ host
    volumes:
      - pg_identity:/var/lib/postgresql/data
    networks: [evnet]

  identity-api:
    build:
      context: .
      dockerfile: src/services/identity-service/IdentityService.Api/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ASPNETCORE_URLS: http://+:8080; https://+:8081
      ConnectionStrings__Default: "Host=identity-db;Port=5432;Database=${IDENTITY_DB_NAME};Username=${IDENTITY_DB_USER};Password=${IDENTITY_DB_PASSWORD}"
    depends_on:
      - identity-db
    ports:
      - "8103:8080" 
    networks: [evnet]
    restart: unless-stopped

  catalog-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_DB: ${CATALOG_DB_NAME}
    ports:
      - "5436:5432"   # để connect từ host
    volumes:
      - pg_catalog:/var/lib/postgresql/data
    networks: [evnet]
  catalog-api:
    build:
      context: .
      dockerfile: src/services/catalog-service/CatalogService.Api/Dockerfile
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ASPNETCORE_URLS: http://+:8080
      GrpcSettings__IdentityServiceUrl: http://identity-service:8081
      LocalFileStorage__BasePath: "wwwroot/uploads"
      ConnectionStrings__Default: "Host=catalog-db;Port=5432;Database=${CATALOG_DB_NAME};Username=${CATALOG_DB_USER};Password=${CATALOG_DB_PASSWORD}"
    depends_on:
      - catalog-db
    ports:
      - "8104:8080"
    volumes:
      - uploads:/app/wwwroot/uploads
    networks: [evnet]
    restart: unless-stopped
