user nginx;
worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream yarp_gateway {
        server api-gateway:80;
    }

    server {
        listen 80;
        server_name api.localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name api.localhost;

        ssl_certificate /etc/nginx/certs/api.localhost.pem;
        ssl_certificate_key /etc/nginx/certs/api.localhost-key.pem;

        root /usr/share/nginx/html;
        index index.html;

        # ==== BACKEND ====
        location /api/ {
            proxy_pass http://yarp_gateway;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }

        # ==== FRONTEND ====
        location / {
            try_files $uri /index.html;
        }
    }
}
